# Generated by Django 5.1.7 on 2025-03-27 16:21

import django.db.models.deletion
import trees.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genus_name', models.CharField(max_length=100, verbose_name='Имя рода')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('changed_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('info', models.TextField(blank=True, verbose_name='Описание')),
                ('is_public', models.BooleanField(default=False, help_text='Поставьте галочку, чтобы сделать древо публичным.', verbose_name='Публичное')),
                ('slug', models.SlugField(help_text='Идентификатор страницы для URL; разрешены символы латиницы, цифры, дефис и подчёркивание.', unique=True, verbose_name='Идентификатор')),
                ('linked_tree', models.ManyToManyField(blank=True, to='trees.tree', verbose_name='Связанное древо')),
                ('owner', models.ForeignKey(on_delete=models.SET(trees.utils.change_owner_or_delete), to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='Имя')),
                ('maiden_name', models.CharField(blank=True, max_length=100, verbose_name='Девичья фамилия')),
                ('patronymic', models.CharField(blank=True, max_length=50, verbose_name='Отчество')),
                ('birthday', models.DateField(blank=True, verbose_name='День рождения')),
                ('date_of_death', models.DateField(blank=True, verbose_name='Дата смерти')),
                ('gender', models.CharField(choices=[('м', 'Мужской'), ('ж', 'Женский')], max_length=1, verbose_name='Пол')),
                ('biography', models.TextField(blank=True, verbose_name='Биография')),
                ('photo', models.ImageField(blank=True, upload_to='person_photo', verbose_name='Фото')),
                ('child', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_child', to='trees.person', verbose_name='Ребёнок')),
                ('father', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_father', to='trees.person', verbose_name='Отец')),
                ('mother', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_mother', to='trees.person', verbose_name='Мать')),
                ('spouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_spouse', to='trees.person', verbose_name='Супруг')),
                ('genus_name', models.ManyToManyField(to='trees.tree', verbose_name='Род')),
            ],
        ),
    ]
