# Generated by Django 5.1.7 on 2025-04-26 19:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='Имя')),
                ('maiden_name', models.CharField(blank=True, max_length=100, verbose_name='Девичья фамилия')),
                ('patronymic', models.CharField(blank=True, max_length=50, verbose_name='Отчество')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='День рождения')),
                ('date_of_death', models.DateField(blank=True, null=True, verbose_name='Дата смерти')),
                ('gender', models.CharField(choices=[('м', 'Мужской'), ('ж', 'Женский')], max_length=1, verbose_name='Пол')),
                ('biography', models.TextField(blank=True, verbose_name='Биография')),
                ('photo', models.ImageField(blank=True, upload_to='person_photo', verbose_name='Фото')),
                ('parents', models.ManyToManyField(blank=True, default='Неизвестно', help_text='Чтобы отменить выбранного человека: ctrl + нажмите имя человека.', related_name='children', to='trees.person', verbose_name='Родители')),
                ('spouse', models.ForeignKey(blank=True, help_text='Чтобы отменить выбранного человека: ctrl + нажмите имя человека.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_spouse', to='trees.person', verbose_name='Супруг')),
            ],
            options={
                'verbose_name': 'член родословной',
                'verbose_name_plural': 'Члены родословной',
                'ordering': ('birthday',),
            },
        ),
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genus_name', models.CharField(max_length=100, verbose_name='Имя рода')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('changed_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('info', models.TextField(blank=True, verbose_name='Описание')),
                ('is_public', models.BooleanField(default=False, help_text='Поставьте галочку, чтобы сделать древо публичным.', verbose_name='Публичное')),
                ('slug', models.SlugField(blank=True, help_text='Идентификатор страницы для URL; разрешены символы латиницы, цифры, дефис и подчёркивание.', unique=True, verbose_name='Идентификатор')),
                ('linked_tree', models.ManyToManyField(blank=True, to='trees.tree', verbose_name='Связанное древо')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='tree_owner', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
                ('progenitor', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tree_progenitor', to='trees.person', verbose_name='Родоначальник')),
            ],
            options={
                'verbose_name': 'Древо',
                'verbose_name_plural': 'Древа',
                'ordering': ('created_at',),
            },
        ),
        migrations.AddField(
            model_name='person',
            name='genus_name',
            field=models.ManyToManyField(related_name='person_id', to='trees.tree', verbose_name='Род'),
        ),
    ]
