# Generated by Django 5.1.7 on 2025-03-29 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ('birthday',), 'verbose_name': 'член родословной', 'verbose_name_plural': 'Члены родословной'},
        ),
        migrations.AlterModelOptions(
            name='tree',
            options={'ordering': ('created_at',), 'verbose_name': 'Древо', 'verbose_name_plural': 'Древа'},
        ),
        migrations.AlterField(
            model_name='person',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='День рождения'),
        ),
        migrations.AlterField(
            model_name='person',
            name='date_of_death',
            field=models.DateField(blank=True, null=True, verbose_name='Дата смерти'),
        ),
        migrations.AlterField(
            model_name='person',
            name='genus_name',
            field=models.ManyToManyField(related_name='person_id', to='trees.tree', verbose_name='Род'),
        ),
    ]
