# Generated by Django 5.1.7 on 2025-03-30 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0002_alter_person_options_alter_tree_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tree',
            name='slug',
            field=models.SlugField(blank=True, help_text='Идентификатор страницы для URL; разрешены символы латиницы, цифры, дефис и подчёркивание.', unique=True, verbose_name='Идентификатор'),
        ),
    ]
