# Generated by Django 5.1.7 on 2025-04-02 09:57

import trees.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0003_alter_tree_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tree',
            name='progenitor',
            field=models.OneToOneField(null=True, on_delete=models.SET(trees.utils.get_progenitor), related_name='tree_progenitor', to='trees.person', verbose_name='Родоначальник'),
        ),
        migrations.AlterField(
            model_name='tree',
            name='owner',
            field=models.ForeignKey(on_delete=models.SET(trees.utils.change_owner_or_delete), related_name='tree_owner', to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
    ]
