# Generated by Django 5.1.7 on 2025-04-02 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0005_alter_tree_progenitor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='child',
        ),
        migrations.AddField(
            model_name='person',
            name='child',
            field=models.ManyToManyField(blank=True, related_name='my_child', to='trees.person', verbose_name='Ребёнок'),
        ),
    ]
