# Generated by Django 5.1.7 on 2025-04-03 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0007_alter_tree_progenitor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='child',
        ),
        migrations.RemoveField(
            model_name='person',
            name='father',
        ),
        migrations.RemoveField(
            model_name='person',
            name='mother',
        ),
        migrations.AddField(
            model_name='person',
            name='level',
            field=models.SmallIntegerField(null=True, verbose_name='Поколение'),
        ),
        migrations.AddField(
            model_name='person',
            name='parents',
            field=models.ManyToManyField(blank=True, related_name='children', to='trees.person', verbose_name='Родители'),
        ),
    ]
