# Generated by Django 5.1.7 on 2025-04-04 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0008_remove_person_child_remove_person_father_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='parents',
            field=models.ManyToManyField(blank=True, default='Неизвестно', related_name='children', to='trees.person', verbose_name='Родители'),
        ),
    ]
