# Generated by Django 5.1.7 on 2025-03-12 11:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familytreeuser',
            name='birthday',
            field=models.DateField(blank=True, default=datetime.date(1, 1, 1), verbose_name='День рождения'),
        ),
    ]
